server:
  port: 8067

eureka:
  instance:
    hostname: localhost
  client:
    # registerWithEureka: true #可不写
    # fetchRegistry: true #可不写
    serviceUrl:
      defaultZone: http://localhost:8060/eureka/

spring:
  application:
    name: service-zuul

# zuul 路由
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
