server:
  port: 8068

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        label: master # 配置仓库的分支
        git:
          uri: https://github.com/runbeyondmove/SpringcloudConfig # 配置git仓库地址
          searchPaths: respo # 配置仓库路径
          username: # 访问git仓库的用户名
          password: # 访问git仓库的用户密码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/