server:
  port: 8068

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        label: master # 配置仓库的分支
        git:
          uri: https://github.com/forezp/SpringcloudConfig/ # 配置git仓库地址
          searchPaths: respo # 配置仓库路径
          username: # 访问git仓库的用户名
          password: # 访问git仓库的用户密码

# 在指定git存库中存在config-client-dev配置文件： 配置项 foo = foo version 3
# 所以访问地址是这样子的：
# http://localhost:8888/foo/dev   即
