server:
  port: 8061

eureka:
  instance:
    hostname: localhost
  client:
    # registerWithEureka: true #可不写
    # fetchRegistry: true #可不写
    serviceUrl:
      defaultZone: http://localhost:8060/eureka/

spring:
  application:
    name: service-hi